DECLARE @DATA_INI VARCHAR(8);
DECLARE @DATA_FIM VARCHAR(8);
DECLARE @FECHAMENTO VARCHAR(8);

/* PERIODO (MES) EM ANÁLISE */
SET @DATA_INI = '20200601'
SET @DATA_FIM = '20200630'

/* DATA DO ULTIMO FECHAMENTO */
SET @FECHAMENTO = '20200531'

SELECT DISTINCT CODIGO FROM

(
	SELECT DISTINCT B9_COD CODIGO
	FROM SB9010 (NOLOCK) 
	WHERE D_E_L_E_T_=''
			AND B9_DATA = @FECHAMENTO
			AND B9_QINI>0
	
	UNION ALL

	SELECT DISTINCT D1_COD CODIGO
	FROM SD1010 A (NOLOCK) 
	WHERE	A.D_E_L_E_T_=''
			AND D1_DTDIGIT BETWEEN @DATA_INI AND @DATA_FIM
	
	UNION ALL

	SELECT DISTINCT D2_COD CODIGO
	FROM SD2010 A (NOLOCK) 
	WHERE	A.D_E_L_E_T_=''
			AND D2_EMISSAO BETWEEN @DATA_INI AND @DATA_FIM
	
	UNION ALL

	SELECT DISTINCT D3_COD CODIGO
	FROM SD3010 A (NOLOCK) 
	WHERE	A.D_E_L_E_T_=''
			AND A.D3_ESTORNO=''
			AND A.D3_TM NOT IN ('200','700')
			AND D3_EMISSAO BETWEEN @DATA_INI AND @DATA_FIM
) AS T1

ORDER BY 1