DECLARE @DTFEC	VARCHAR(8);
DECLARE @DTINI	VARCHAR(8);
DECLARE @DTFIM	VARCHAR(8);
DECLARE @CODINI	VARCHAR(6);
DECLARE @CODFIM	VARCHAR(6);

SET @DTFEC = '20191231'
SET @DTINI = '20200101'
SET @DTFIM = '20200131'
SET @CODINI = ''
SET @CODFIM = 'ZZZZZZZ'

SELECT SUM(B9_VINI1) VALOR,SUM(B9_QINI) QTD
FROM SB9010 A
WHERE	A.D_E_L_E_T_=''
		AND A.B9_DATA = @DTFEC
		AND (A.B9_QINI!=0 OR A.B9_VINI1!=0)
		--AND A.B9_QINI!=0
		AND A.B9_COD BETWEEN @CODINI AND @CODFIM

SELECT SUM(D1_CUSTO) CUSTO,SUM(D1_QUANT) QTD
FROM SD1010 A
INNER JOIN SF4010 B ON B.D_E_L_E_T_='' AND B.F4_CODIGO=A.D1_TES AND B.F4_ESTOQUE = 'S'
WHERE	A.D_E_L_E_T_=''
		AND D1_DTDIGIT BETWEEN @DTINI AND @DTFIM
		AND D1_COD BETWEEN @CODINI AND @CODFIM 

SELECT SUM(D2_CUSTO1) CUSTO,SUM(D2_CUSTO1)/SUM(D2_QUANT),SUM(D2_QUANT) QTD
FROM SD2010 A
INNER JOIN SF4010 B ON B.D_E_L_E_T_='' AND B.F4_CODIGO=A.D2_TES AND B.F4_ESTOQUE = 'S'
WHERE	A.D_E_L_E_T_=''
		AND D2_EMISSAO BETWEEN @DTINI AND @DTFIM
		AND D2_COD BETWEEN @CODINI AND @CODFIM 

SELECT D3_TM,SUM(D3_CUSTO1) CUSTO, SUM(D3_QUANT) QTD
FROM SD3010 A
WHERE	A.D_E_L_E_T_=''
		AND D3_EMISSAO BETWEEN @DTINI AND @DTFIM
		AND D3_COD BETWEEN @CODINI AND @CODFIM 
		AND D3_ESTORNO=''
	--	AND D3_TM NOT IN ('499','999')
GROUP BY D3_TM
ORDER BY D3_TM

SELECT SUM(B9_VINI1) VALOR,SUM(B9_QINI) QTD
FROM SB9010 A
WHERE	A.D_E_L_E_T_=''
		AND A.B9_DATA = @DTFIM
		AND (A.B9_QINI!=0 OR A.B9_VINI1!=0)
		AND A.B9_COD BETWEEN @CODINI AND @CODFIM

